name = "ScaraModel"
uuid = "27901c50-6945-4cd6-ab00-676371e32c25"
authors = ["Andreas Hofmann <andreas.hofmann@uni-a.de>"]
version = "0.1.0"

[deps]
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
ModelingToolkitStandardLibrary = "16a59e39-deab-5bd0-87e4-056b12336739"
NaNMath = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"

[compat]
DataInterpolations = "8.6.1"
DelimitedFiles = "1.9.1"
DifferentialEquations = "7.16.1"
HDF5 = "0.17.2"
ModelingToolkit = "10.26.0"
ModelingToolkitStandardLibrary = "2.25.0"
NaNMath = "1.1.3"
